# Generated by Django 5.0.3 on 2024-05-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Precio por Unidad'),
            preserve_default=False,
        ),
    ]
