# Generated by Django 5.0.3 on 2024-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_materiales_numero_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='es_habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
