# Generated by Django 5.0.3 on 2024-04-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_clasificacion', models.CharField(error_messages={'unique': 'El nombre de la categoria ya existe'}, max_length=100, unique=True)),
                ('nombre', models.CharField(error_messages={'unique': 'El codigo de la categoria ya existe    '}, max_length=200, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tamaño', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
