# Generated by Django 5.0.3 on 2024-04-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad_paquete',
            field=models.IntegerField(verbose_name='Cantidad por paquetes'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad_unidad',
            field=models.IntegerField(verbose_name='Cantidad por unidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='numero_serie',
            field=models.CharField(blank=True, error_messages={'unique': 'El numero de serie de producto ya existe'}, max_length=255, null=True, unique=True, verbose_name='Numero de serie'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_paquete',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por paquetes'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por unidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidad de medida'),
        ),
    ]
