# Generated by Django 5.0.3 on 2024-04-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='total_paquetes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='total_precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
