# Generated by Django 5.0.3 on 2024-04-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
