# Generated by Django 5.0.3 on 2024-04-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_total_paquetes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='total_paquetes',
            new_name='stock',
        ),
    ]
