# Generated by Django 5.0.3 on 2024-04-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
