# Generated by Django 5.0.3 on 2024-04-22 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
