# Generated by Django 5.0.3 on 2024-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='es_habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
