# Generated by Django 5.0.3 on 2024-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='area_trabajo',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Personal', 'Personal')], default='Personal', null=True),
        ),
    ]
