# Generated by Django 5.0.3 on 2024-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='encargado_unidad',
            field=models.BooleanField(choices=[(True, 'Jefe de la unidad'), (False, 'No es jefe de la unidad')], default=False),
            preserve_default=False,
        ),
    ]
