# Generated by Django 5.0.3 on 2024-07-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.RemoveField(
            model_name='oficinas',
            name='area',
        ),
        migrations.RemoveField(
            model_name='direccion_departamental',
            name='area',
        ),
        migrations.RemoveField(
            model_name='direccion_departamental',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion_departamental',
        ),
        migrations.RemoveField(
            model_name='direccion_servicios',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='servicios',
        ),
        migrations.AddField(
            model_name='oficinas',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.unidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.oficinas'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Direccion_departamental',
        ),
        migrations.DeleteModel(
            name='Direccion_servicios',
        ),
    ]
