# Generated by Django 5.0.3 on 2024-07-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccion_servicios_remove_usuario_mango_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='area',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='oficina',
        ),
        migrations.AddField(
            model_name='unidad',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.secretaria'),
        ),
    ]
