# Generated by Django 5.0.3 on 2024-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_encargado_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='encargado_secretaria',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Personal', 'Personal')], default=False, verbose_name='Encargado de la secretaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='encargado_unidad',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Personal', 'Personal')], default=False, verbose_name='Encargado secretaria'),
        ),
    ]
