# Generated by Django 5.0.3 on 2024-05-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_encargado_secretaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='encargado_unidad',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Personal', 'Personal')], default=False, verbose_name='Encargado unidad'),
        ),
    ]
