# Generated by Django 5.0.3 on 2024-06-28 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_persona_cedula_identidad'),
        ('usuarios', '0003_usuario_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pedidos_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.area_trabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.secretaria'),
        ),
    ]
