# Generated by Django 5.0.3 on 2024-05-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_encargado_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre_rol',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='secretaria',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='encargado_secretaria',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Personal', 'Personal')], default=False, verbose_name='Jefe  de la secretaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='encargado_unidad',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Personal', 'Personal')], default=False, verbose_name='Jefe de la unidad'),
        ),
    ]
