# Generated by Django 5.0.3 on 2024-07-10 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_pedidos_general_alter_usuario_area_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_trabajo',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Axuliar', 'Axuliar'), ('Personal', 'Personal')], default='Personal', null=True),
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
