# Generated by Django 5.0.3 on 2024-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_roles_nombre_rol_alter_secretaria_secretaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='secretaria',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
