# Generated by Django 5.0.3 on 2024-07-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_area_trabajo_rol_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='editar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eliminar',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='permisos',
        ),
    ]
