# Generated by Django 5.0.3 on 2024-07-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_crear_usuario_editar_usuario_eliminar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_trabajo',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Axuliar', 'Axuliar'), ('Personal', 'Personal')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='crear',
            field=models.BooleanField(default=False, verbose_name='Crear material'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='editar',
            field=models.BooleanField(default=False, verbose_name='editar material'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='eliminar',
            field=models.BooleanField(default=False, verbose_name='Eliminar material'),
        ),
    ]
