# Generated by Django 5.0.3 on 2024-07-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_area_trabajo_rol_alter_usuario_crear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_trabajo',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Axuliar', 'Axuliar'), ('Personal', 'Personal')], default='Personal', null=True),
        ),
    ]
