# Generated by Django 5.0.3 on 2024-07-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_area_trabajo_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_trabajo',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Axuliar', 'Axuliar'), ('Personal', 'Personal')], default='Personal', max_length=250),
        ),
    ]
