# Generated by Django 5.0.3 on 2024-04-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('unidad_manejo', models.CharField(max_length=20)),
                ('cantidad_pedido', models.IntegerField()),
                ('cantidad_entrega_almacen', models.IntegerField()),
                ('partida_presupuestada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_autorizacion', models.CharField(choices=[('Autorizado', 'Autorizado'), ('No autorizado', 'No autorizado')], default='No autorizado')),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Incompleto', 'Incompleto'), ('Completo', 'Completo')], default='Pendiente')),
                ('productos', models.ManyToManyField(through='pedidos.DetallePedido', to='productos.productos')),
            ],
        ),
    ]
