# Generated by Django 5.0.3 on 2024-08-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido_almacen',
            field=models.CharField(default='Pendiente'),
        ),
        migrations.DeleteModel(
            name='Entrega_almacen',
        ),
    ]
