# Generated by Django 5.0.3 on 2024-05-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_es_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
