# Generated by Django 5.0.3 on 2024-05-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_autorizacion_presupuestada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
