# Generated by Django 5.0.3 on 2024-05-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_estado_autorizacion_presupuestada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='es_habilitado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_de_autorizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
