# Generated by Django 5.0.3 on 2024-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_pedido_es_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido_unidad_mayor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
