# Generated by Django 5.0.3 on 2024-05-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_estado_pedido_unidad_mayor_rechazar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado_autorizacion_unidad',
        ),
    ]
