# Generated by Django 5.0.3 on 2024-05-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_estado_autorizacion_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado_autorizacion_unidad_mayor',
        ),
    ]
