# Generated by Django 5.0.3 on 2024-06-28 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_materiales_stock'),
        ('pedidos', '0013_remove_pedido_estado_autorizacion_unidad_mayor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado_autorizacion_director_administrativo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_autorizacion_presupuestada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_autorizacion_unidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido_unidad_mayor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido_unidad_mayor_rechazar',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_de_autorizacion',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiales.materiales'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
