# Generated by Django 5.0.3 on 2024-06-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_remove_pedido_estado_autorizacion_director_administrativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido_almacen',
        ),
    ]
