# Generated by Django 5.0.3 on 2024-06-28 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_remove_pedido_estado_pedido_almacen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_autorizacion', models.BooleanField(default=False)),
                ('fecha_de_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedidos.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega_almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido_almacen', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Incompleto', 'Incompleto'), ('Completo', 'Completo')], default='Pendiente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedidos.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
