# Generated by Django 5.0.3 on 2024-06-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_autorizacion_pedido_entrega_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacion_pedido',
            name='fecha_de_autorizacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
