# Generated by Django 5.0.3 on 2024-06-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_autorizacion_pedido_fecha_de_autorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido',
        ),
    ]
