# Generated by Django 5.0.3 on 2024-04-01 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fecha_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='fecha_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
