# Generated by Django 5.0.3 on 2024-04-01 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_alter_user_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.person'),
        ),
    ]
