# Generated by Django 5.0.3 on 2024-04-14 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_remove_product_categoria_remove_person_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persona',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
