# Generated by Django 5.0.3 on 2024-04-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_rename_person_persona_proveedor_fecha_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='cedulaIdentidad',
            new_name='cedula_identidad',
        ),
    ]
